MOOD_LIST = [
    "Happy",
    "Contemplating Python",
    "Looking at PHP",
    "I'm here aren't I?",
    "Incoherent screaming",
    "AAAAAAAAAAAAAAAAAA",
    "Surprised that this works tbh",
    "Marveling at the mastodon API",
    "Thinking of better moods to add to this list",
    "Oh no, someone submitted this mood to my list!",
    "booM",
    "Mood!",
    "Mooooood 🐄",
    "Here I am, brain the size of a planet, and they ask me to update their mastodon profile.",
    "Mah Nà Mah Nà",
    "Submit a PR",
]
