import random

MOOD_LIST = [
    "Contemplating Python",
    "Looking at PHP",
    "Incoherent screaming",
    "AAAAAAAAAAAAAAAAAA",
    "Surprised that this works tbh",
    "Marveling at the mastodon API",
    "Thinking of better moods to add to this list",
    "Oh no, someone submitted this mood to my list!",
    "booM",
    "Mood!",
    "Mooooood 🐄",
    "Here I am, brain the size of a planet, and they ask me to update their mastodon profile.",
    "Mah Nà Mah Nà",
    "Submit a PR",
    {
        "label": "insert_label_here",
        "content": "insert_content_here",
    },
    "evil",
    "meow",
    "zzzzzzzzzz",
    "now breathing consciously",
    "now blinking consciously",
    "*whistles innocently*",
    "reticulating splines",
    r"X5O!P%@AP[4\PZX54(P^)7CC)7}$EICAR-STANDARD-ANTIVIRUS-TEST-MOOD!$H+H*",
    "[object Object]",
    "~nyaaaa",
    "OwO notices ur https://tnt.tools/ghmfc",
    ":blobfoxpleading: :blobfoxblush:",
    "am gay uwu",
    "foxes? in this brain? it's more likely than you think",
    "Right now, I'm just looking at your profile.",
    "🥺👉👈",
    "Not involved in human trafficking",
    "training foxes to edit Wikipedia",
    "100% asbestos-free",
    'voted "Cutest Cat Ears" this side of the Atlantic',
    "does not fulfill a structural need",
    "Wololo 🙏",
    "is not oomf",
    "thinking about bees",
    {
        "label": "Fact",
        "content": "Foxes are just cat software running on dog hardware.",
    },
    "not plotting the next evil scheme for the Fox Cabal",
    "[fox screm]",
    "looking at a blåhaj",
    "looking at a gay blåhaj",
    {
        "label": "Gay",
        "content": "Yes",
    },
    {
        "label": "Snoot boops today",
        "content": str(random.randint(1, 20)),
    },
    "See https://en.wikipedia.org/wiki/Help:Magic_words",
    ":3",
    {
        "label": "Fun Fact",
        "content": "I'm not a catgirl :3",
    },
    "awawawawa",
    "I'm not a robot, I'm a fox!",
    "I'm not a fox, I'm a robot!",
    {
        "label": "Scoville Heat Units",
        "content": "1,500,000 SHU",
    },
    "What even is a dict",
    "What even is a list",
    {
        "label": "awoooo?",
        "content": "yes",
    },
    {
        "label": "GREEN!",
        "content": "PURPLE!",
    },
    {
        "label": "Favourite percussion instrument",
        "content": "EWOULDBLOCK",
    },
    {
        "label": "Traceback (most recent call last):",
        "content": "IndexError: list index out of range",
    },
    "Past tense of moo",
    "fops",
    "fox",
    "fopks",
    "fokps",
    {
        "label": "merge",
        "content": "conflicted"
    },
    "eepy",
    "eepn't",
    "in 'detached HEAD' state",
]
