MOOD_LIST = [
    "Happy",
    "Contemplating Python",
    "Looking at PHP",
    "I'm here aren't I?",
    "Incoherent screaming",
    "AAAAAAAAAAAAAAAAAA",
    "Surprised that this works tbh",
    "Marveling at the mastodon API",
    "Thinking of better moods to add to this list",
    "Oh no, someone submitted this mood to my list!",
    "booM",
    "Mood!",
    "Mooooood 🐄",
    "Here I am, brain the size of a planet, and they ask me to update their mastodon profile.",
    "Mah Nà Mah Nà",
    "Submit a PR",
    "evil",
    "meow",
    "zzzzzzzzzz",
    "now breathing consciously",
    "now blinking consciously",
    "*whistles innocently*",
    "reticulating splines",
    r"X5O!P%@AP[4\PZX54(P^)7CC)7}$EICAR-STANDARD-ANTIVIRUS-TEST-MOOD!$H+H*",
    "[object Object]",
    "~nyaaaa",
    "OwO notices ur https://tnt.tools/ghmfc",
    ":blobfoxpleading: :blobfoxblush:",
    "am gay uwu",
    "foxes? in this brain? it's more likely than you think",
    "Right now, I'm just looking at your profile.",
    "🥺👉👈",
    "Not involved in human trafficking",
    "training foxes to edit Wikipedia",
    "100% asbestos-free",
    'voted "Cutest Cat Ears" this side of the Atlantic',
]
